import type { Metadata } from "next";
import { Tomorrow } from "next/font/google";
import "./globals.css";
import { Header } from "../components/header";
import { Gap } from "@/components/gap";
import { Footer } from "@/components/footer";

const tomorrow = Tomorrow({
  subsets: ["latin"],
  variable: "--font-tomorrow",
  weight: [
    "100",
    "200",
    "300",
    "400",
    "500",
    "600",
    "700",
    "800",
    "900",
  ],
});


export const metadata: Metadata = {
  title: "Gabriel Maia Dev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt">
      <body
        className={`${tomorrow.variable} antialiased text-foreground min-h-screen flex flex-col md:mx-15`}
      >
        <Gap />
        <Header />
        <main className="border-x border-zinc-200 dark:border-zinc-900">
        {children}
        </main>
        <Footer />
        <Gap />
      </body>
    </html>
  );
}
